# fly.toml app configuration file for telegram-moderator
# This configuration ensures the app runs continuously.

app = "telegram-moderator"
primary_region = "ams"

# Вказуємо, яку команду запускати
[processes]
  app = "python bot.py"

# Цей блок - це "трюк", який змушує машину працювати постійно.
# Він описує фальшивий сервіс, що дозволяє нам керувати авто-зупинкою.
[[services]]
  internal_port = 8080 # Цей порт не має значення, він просто має бути
  processes = ["app"]
  protocol = "tcp"

  # Ці два рядки - найголовніші. Вони забороняють машині "засинати".
  auto_stop_machines = false
  min_machines_running = 1