# fly.toml app configuration file for telegram-moderator
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "telegram-moderator"
primary_region = "ams" # Ваш регіон, можна залишити як є

# Вказуємо Fly.io, що це не веб-сервер, а постійний процес.
# Він буде запущений командою "python bot.py".
[processes]
  app = "python bot.py"