name: Fly Deploy

on:
  push:
    branches:
      - master # Ваша основна гілка

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    
    steps:
      # Крок 1: Завантажуємо код з репозиторію
      - uses: actions/checkout@v3

      # Крок 2: Встановлюємо flyctl (актуальний екшен)
      - uses: superfly/fly-actions/setup-flyctl@master

      # Крок 3: Розгортаємо додаток, передаючи секрети
      - run: >
          flyctl deploy --remote-only
          --set-secret TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          --set-secret TELEGRAM_ADMIN_CHAT_ID=${{ secrets.TELEGRAM_ADMIN_CHAT_ID }}
          --set-secret TELEGRAM_MODERATOR_CHAT_ID=${{ secrets.TELEGRAM_MODERATOR_CHAT_ID }}
          --set-secret RULES_URL=${{ secrets.RULES_URL }}
          --set-secret BANNED_WORDS=${{ secrets.BANNED_WORDS }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}