name: Fly Deploy

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set secrets
        run: |
          flyctl secrets set --app telegram-moderator \
            TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}" \
            TELEGRAM_ADMIN_CHAT_ID="${{ secrets.TELEGRAM_ADMIN_CHAT_ID }}" \
            TELEGRAM_MODERATOR_CHAT_ID="${{ secrets.TELEGRAM_MODERATOR_CHAT_ID }}" \
            RULES_URL="${{ secrets.RULES_URL }}" \
            BANNED_WORDS="${{ secrets.BANNED_WORDS }}"

      - name: Deploy to Fly.io
        run: flyctl deploy --app telegram-moderator --remote-only