name: Fly Deploy

on:
  # Запускати автоматично при кожному пуші в основну гілку
  push:
    branches:
      - master # Якщо ваша основна гілка називається master, змініть main на master

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/fly-pr-review-apps@1.2
        with:
          fly_api_token: ${{ secrets.FLY_API_TOKEN }}
          # Передаємо всі секрети з GitHub у додаток на Fly.io
          secrets: |
            TELEGRAM_BOT_TOKEN
            TELEGRAM_ADMIN_CHAT_ID
            TELEGRAM_MODERATOR_CHAT_ID
            RULES_URL
            BANNED_WORDS